//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credenciales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_user { get; set; }
        public string Usuario { get; set; }
        public string Contra { get; set; }
        public string Nombre { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Tipo_Usuario { get; set; }
    }
}
