//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credenciales.Models.Credenciales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Credenciales
    {
        public int Id { get; set; }
        public string Nombre_Comp { get; set; }
        public string Area { get; set; }
        public string Telefono { get; set; }
        public string Whatsapp { get; set; }
        public string Correo { get; set; }
        public string Fotografía { get; set; }
        public string num_emp { get; set; }
    }
}
